//
// Created by Kamel on 15/12/2022.
//

import SwiftUI

public enum AppSystemImage: String {
    case chevronForward = "chevron.forward"
    case chevronBackward = "chevron.backward"
    case chevronDown = "chevron.down"
    case ellipsis = "ellipsis"
    case magnifyingGlass = "magnifyingglass"
    case checkmarkSquareFill = "checkmark.square.fill"
    case square = "square"
    case squareAndPencil = "square.and.pencil"
    case squareAndArrowUpCircleFill = "square.and.arrow.up.circle.fill"
    case squareAndArrowUpCircle = "square.and.arrow.up.circle"
    case trashCircleFill = "trash.circle.fill"
    case xMarkCircleFill = "xmark.circle.fill"
    case xMark = "xmark"
    case checkmarkCircleFill = "checkmark.circle.fill"
    case calendar = "calendar"
    case infoCircle = "info.circle"
    case infoCircleFill = "info.circle.fill"
    case info = "info"
    case arrowBackward = "arrow.backward"
    case trash = "trash"
    case trashFill = "trash.fill"
    case trashCircle = "trash.circle"
    case arrowForward = "arrow.forward"
    case checkmarkSealFill = "checkmark.seal.fill"
    case checkmark = "checkmark"
    case exclamationMarkTriangle = "exclamationmark.triangle"
    case phone = "phone"
    case phoneFill = "phone.fill"
    case phoneCircle = "phone.circle"
    case phoneBadgePlus = "phone.badge.plus"
    case phoneFillBadgePlus = "phone.fill.badge.plus"
    case phoneArrowUpRight = "phone.arrow.up.right"
    case phoneFillArrowUpRight = "phone.fill.arrow.up.right"
    case phoneFillArrowDownLeft = "phone.fill.arrow.down.left"
    case phoneArrowDownLeft = "phone.arrow.down.left"
    case bellFill = "bell.fill"
    case arrowLeftSquareFill = "arrow.left.square.fill"
    case arrowRightSquareFill = "arrow.right.square.fill"
    case envelope = "envelope"
    case globe = "globe"
    case circleInsetFilled = "circle.inset.filled"
    case circleFill = "circle.fill"
    case playFill = "play.fill"
    case playCircleFill = "play.circle.fill"
    case playCircle = "play.circle"
    case plus = "plus"
    case plusCircleFill = "plus.circle.fill"
    case plusCircle = "plus.circle"
    case plusSquareDashed = "plus.square.dashed"
    case icloudAndArrowUpFill = "icloud.and.arrow.up.fill"
    case exclamationMarkTriangleFill = "exclamationmark.triangle.fill"
    case exclamationMarkCircleFill = "exclamationmark.circle.fill"
    case pinFill = "pin.fill"
    case line3Horizontal = "line.3.horizontal"
    case checkmarkRectanglePortraitFill = "checkmark.rectangle.portrait.fill"
    case checkmarkRectanglePortrait = "checkmark.rectangle.portrait"
    case docOnDocFill = "doc.on.doc.fill"
    case docOnDoc = "doc.on.doc"
    case arrowTriangleDownFill = "arrowtriangle.down.fill"
    case micSlash = "mic.slash"
    case circleGrid3x3 = "circle.grid.3x3"
    case personFillBadgePlus = "person.fill.badge.plus"
    case pauseFill = "pause.fill"
    case speakerWave3 = "speaker.wave.3"
    case arrowTriangleMerge = "arrow.triangle.merge"
    case deleteBackwardFill = "delete.backward.fill"
    case faceId = "faceid"
    case touchId = "touchid"
    case checkmarkShieldFill = "checkmark.shield.fill"
    case xMarkShieldFill = "xmark.shield.fill"
    case chevronLeft = "chevron.left"
    case multiply = "multiply"
    case plusAppFill = "plus.app.fill"
    case minusCircleFill = "minus.circle.fill"
    case person2CircleFill = "person.2.circle.fill"
    case messageFill = "message.fill"
    case personCropCircleBadgeExclamationMarkFill = "person.crop.circle.badge.exclamationmark.fill"
    case chevronRight = "chevron.right"
    case faceSmilingFill = "face.smiling.fill"
    case phoneDownCircleFill = "phone.down.circle.fill"
    case trayAndArrowUpFill = "tray.and.arrow.up.fill"
    case envelopeBadgeFill = "envelope.badge.fill"
    case noSign = "nosign"
    case trayAndArrowDownFill = "tray.and.arrow.down.fill"
    case trayFill = "tray.fill"
    case wandAndStars = "wand.and.stars"
    case camera = "camera"
    case circle = "circle"
    case squareAndArrowDownFill = "square.and.arrow.down.fill"
    case arrowDownCircle = "arrow.down.circle"
    case questionMarkCircle = "questionmark.circle"
    case questionMarkCircleFill = "questionmark.circle.fill"
    case arrowShapeTurnUpLeft = "arrowshape.turn.up.left"
    case arrowShapeTurnUpLeftFill = "arrowshape.turn.up.left.fill"
    case textBadgeCheckmark = "text.badge.checkmark"
    case rectangle3OffGridBubbleLeftFill = "rectangle.3.offgrid.bubble.left.fill"
    case puzzlePieceFill = "puzzlepiece.fill"
    case personFill = "person.fill"
    case musicNote = "music.note"
    case powerSleep = "powersleep"
    case gear = "gear"
    case heartCircleFill = "heart.circle.fill"
    case heartFill = "heart.fill"
    case gameControllerFill = "gamecontroller.fill"
}

public extension Image {
    init(systemName: AppSystemImage) {
        self.init(systemName: systemName.rawValue)
    }
}

public extension UIImage {
    convenience init?(systemName: AppSystemImage) {
        self.init(systemName: systemName.rawValue)
    }
}

