stages:
  - test_flight

variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"

before_script:
  - gem install bundler
  - bundle install

test_flight_build:
  dependencies: []
  stage: test_flight
  script:
    - fastlane testflight_distribute_release
  tags:
    - ios
  only:
    - /^releases.*$/